/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/_admin.users'
import { Route as AdminTasksIndexRouteImport } from './routes/_admin.tasks.index'
import { Route as AdminTasksNewRouteImport } from './routes/_admin.tasks.new'
import { Route as AdminTasksTaskIdIndexRouteImport } from './routes/_admin.tasks.$taskId.index'
import { Route as AdminTasksTaskIdEditRouteImport } from './routes/_admin.tasks.$taskId.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksNewRoute = AdminTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksTaskIdIndexRoute = AdminTasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksTaskIdEditRoute = AdminTasksTaskIdEditRouteImport.update({
  id: '/tasks/$taskId/edit',
  path: '/tasks/$taskId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users': typeof AdminUsersRoute
  '/tasks/new': typeof AdminTasksNewRoute
  '/tasks/': typeof AdminTasksIndexRoute
  '/tasks/$taskId/edit': typeof AdminTasksTaskIdEditRoute
  '/tasks/$taskId/': typeof AdminTasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users': typeof AdminUsersRoute
  '/tasks/new': typeof AdminTasksNewRoute
  '/tasks': typeof AdminTasksIndexRoute
  '/tasks/$taskId/edit': typeof AdminTasksTaskIdEditRoute
  '/tasks/$taskId': typeof AdminTasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/tasks/new': typeof AdminTasksNewRoute
  '/_admin/tasks/': typeof AdminTasksIndexRoute
  '/_admin/tasks/$taskId/edit': typeof AdminTasksTaskIdEditRoute
  '/_admin/tasks/$taskId/': typeof AdminTasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/users'
    | '/tasks/new'
    | '/tasks/'
    | '/tasks/$taskId/edit'
    | '/tasks/$taskId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/users'
    | '/tasks/new'
    | '/tasks'
    | '/tasks/$taskId/edit'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/users'
    | '/_admin/tasks/new'
    | '/_admin/tasks/'
    | '/_admin/tasks/$taskId/edit'
    | '/_admin/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tasks/': {
      id: '/_admin/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AdminTasksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tasks/new': {
      id: '/_admin/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AdminTasksNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tasks/$taskId/': {
      id: '/_admin/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof AdminTasksTaskIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tasks/$taskId/edit': {
      id: '/_admin/tasks/$taskId/edit'
      path: '/tasks/$taskId/edit'
      fullPath: '/tasks/$taskId/edit'
      preLoaderRoute: typeof AdminTasksTaskIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminTasksNewRoute: typeof AdminTasksNewRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
  AdminTasksTaskIdEditRoute: typeof AdminTasksTaskIdEditRoute
  AdminTasksTaskIdIndexRoute: typeof AdminTasksTaskIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminTasksNewRoute: AdminTasksNewRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
  AdminTasksTaskIdEditRoute: AdminTasksTaskIdEditRoute,
  AdminTasksTaskIdIndexRoute: AdminTasksTaskIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
