/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin.users.index'
import { Route as AdminTasksIndexRouteImport } from './routes/_admin.tasks.index'
import { Route as AdminTasksNewRouteImport } from './routes/_admin.tasks.new'
import { Route as AdminUsersUserIdIndexRouteImport } from './routes/_admin.users.$userId.index'
import { Route as AdminUsersUserIdEditRouteImport } from './routes/_admin.users.$userId.edit'
import { Route as AdminTasksTaskIdIndexRouteImport } from './routes/_admin.tasks.$taskId.index'
import { Route as AdminTasksTaskIdEditRouteImport } from './routes/_admin.tasks.$taskId.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksNewRoute = AdminTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdIndexRoute = AdminUsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdEditRoute = AdminUsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksTaskIdIndexRoute = AdminTasksTaskIdIndexRouteImport.update({
  id: '/tasks/$taskId/',
  path: '/tasks/$taskId/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksTaskIdEditRoute = AdminTasksTaskIdEditRouteImport.update({
  id: '/tasks/$taskId/edit',
  path: '/tasks/$taskId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks/new': typeof AdminTasksNewRoute
  '/users/': typeof AdminUsersIndexRoute
  '/tasks/': typeof AdminTasksIndexRoute
  '/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/tasks/$taskId/edit': typeof AdminTasksTaskIdEditRoute
  '/tasks/$taskId/': typeof AdminTasksTaskIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks/new': typeof AdminTasksNewRoute
  '/users': typeof AdminUsersIndexRoute
  '/tasks': typeof AdminTasksIndexRoute
  '/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/users/$userId': typeof AdminUsersUserIdIndexRoute
  '/tasks/$taskId/edit': typeof AdminTasksTaskIdEditRoute
  '/tasks/$taskId': typeof AdminTasksTaskIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/users/': typeof AdminUsersIndexRoute
  '/_admin/tasks/': typeof AdminTasksIndexRoute
  '/_admin/tasks/new': typeof AdminTasksNewRoute
  '/_admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/_admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/_admin/tasks/$taskId/edit': typeof AdminTasksTaskIdEditRoute
  '/_admin/tasks/$taskId/': typeof AdminTasksTaskIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tasks/new'
    | '/users/'
    | '/tasks/'
    | '/users/$userId/edit'
    | '/users/$userId/'
    | '/tasks/$taskId/edit'
    | '/tasks/$taskId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tasks/new'
    | '/users'
    | '/tasks'
    | '/users/$userId/edit'
    | '/users/$userId'
    | '/tasks/$taskId/edit'
    | '/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/users/'
    | '/_admin/tasks/'
    | '/_admin/tasks/new'
    | '/_admin/users/$userId/edit'
    | '/_admin/users/$userId/'
    | '/_admin/tasks/$taskId/edit'
    | '/_admin/tasks/$taskId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tasks/': {
      id: '/_admin/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AdminTasksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tasks/new': {
      id: '/_admin/tasks/new'
      path: '/tasks/new'
      fullPath: '/tasks/new'
      preLoaderRoute: typeof AdminTasksNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/$userId/': {
      id: '/_admin/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof AdminUsersUserIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/$userId/edit': {
      id: '/_admin/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AdminUsersUserIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tasks/$taskId/': {
      id: '/_admin/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof AdminTasksTaskIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tasks/$taskId/edit': {
      id: '/_admin/tasks/$taskId/edit'
      path: '/tasks/$taskId/edit'
      fullPath: '/tasks/$taskId/edit'
      preLoaderRoute: typeof AdminTasksTaskIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminTasksNewRoute: typeof AdminTasksNewRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
  AdminUsersUserIdEditRoute: typeof AdminUsersUserIdEditRoute
  AdminUsersUserIdIndexRoute: typeof AdminUsersUserIdIndexRoute
  AdminTasksTaskIdEditRoute: typeof AdminTasksTaskIdEditRoute
  AdminTasksTaskIdIndexRoute: typeof AdminTasksTaskIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminTasksNewRoute: AdminTasksNewRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
  AdminUsersUserIdEditRoute: AdminUsersUserIdEditRoute,
  AdminUsersUserIdIndexRoute: AdminUsersUserIdIndexRoute,
  AdminTasksTaskIdEditRoute: AdminTasksTaskIdEditRoute,
  AdminTasksTaskIdIndexRoute: AdminTasksTaskIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
